name: Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configurar e instalar node-18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalar dependencias
        run: npm ci
      # - name: Realizamos pruebas unitarias
      #   run: npm test
      - name: Build en el servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 177.222.53.32
          username: univalle
          password: 1234abc
          port: 22
          script: whoami